### ISSUE TITLE
Deploy static site to lib-static-prod1

### ISSUE THREAD

**Issue by axamei** [pulibrary/milberg_exhibit_archive#2]
https://github.com/pulibrary/milberg-wp/tree/static-site

Making this site static so we do not have to update / maintain the wordpress site.

**Comment by carolyncole** [comment]
Depends on https://github.com/pulibrary/princeton_ansible/issues/969

**Comment by carolyncole** [comment]
We are waiting on the new certificate for milberg.princeton.edu.  We will need to include that into nginxplus in ansible and have the network entry changed to point to the load balancer.

**Comment by axamei** [comment]
This was completed.
